# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
