# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 02:14
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181008_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='header',
            field=models.ImageField(default='static/upload/3.jpg', upload_to='static/upload/herder', verbose_name='用户头像'),
        ),
    ]
